### ISSUE TITLE
unable to access Foods route via Index.js

### ISSUE THREAD

**Issue by Eddycodes27** [WDI-SEA/project-2-issues#25]
![Screen Shot 2021-11-16 at 9 58 53 AM](https://user-images.githubusercontent.com/91762173/142009349-ab356379-e3d8-4b71-b038-9cc33d7aed98.png)

**Comment by tkolsrud** [comment]
would you mind throwing a screenshot of your food.js file as well?

**Comment by Eddycodes27** [comment]
![Screen Shot 2021-11-16 at 10 06 01 AM](https://user-images.githubusercontent.com/91762173/142010500-f5a4c193-31f8-4083-9e91-f78564026321.png)

**Comment by tkolsrud** [comment]
And one more of the file structure plz

**Comment by Eddycodes27** [comment]
![Screen Shot 2021-11-16 at 10 10 31 AM](https://user-images.githubusercontent.com/91762173/142011259-2625548e-8bc3-432a-a2fc-b44cb68bd88b.png)

**Comment by tkolsrud** [comment]
any luck getting that route going with the boilerplate?

**Comment by Eddycodes27** [comment]
Currently working on getting the new template up and running with my previous things.

**Comment by TaylorDarneille** [comment]
Because the route is inside the controller, if you add `/foods` as the url pattern, you've created a route for `/foods/foods`, and I'm guessing you're trying to make it just be `/foods`. The controller middleware processes the '/foods', then send the remaining url pattern to the controller. So, if your intended route is `/foods', you need to change the url pattern in the route to be `/`

**Comment by Eddycodes27** [comment]
Thank you Taylor, that did it.
