### ISSUE TITLE
more general q: http statuses

### ISSUE THREAD

**Issue by Mackmiller** [WDI-SEA/project-2-issues#39]
What do you guys recommend as a good starting place for incorporating http statuses in this project? I've read up documentation and examples, but not sure how to apply them in this context?

**Comment by timmshinbone** [comment]
Here's a code block I found on stack overflow that kinda quickly gives a sample of how to utilize statuses with res.render. Since we're using a templating language(ejs) we're not really making you worry about statuses, those become more important when your API is JUST returning some JSON data to be consumed by an external client. 
```js
res.render('template', function(err, html) {
   res.send({
     status: "xyz",
     timestamp: new Date(),
     htmlContent: html
   });
});
```
Notice how they included a `res.send` in the callback function, read up on res.send in conjunction with a `res.render`

**Comment by Mackmiller** [comment]
That helps a lot- I hadn't searched about how `res.render` would be involved. Thanks!
